# 파이썬 기초 사전자료

**과제는 중간중간 별표로 표시된 부분을 스스로 채워서 코드 작성한 뒤 제출하시면 됩니다.**

## Python Programming

### 변수와 자료형

**변수**
* 데이터를 특정 이름을 붙여 저장함
* 연산을 쉽게 처리하거나, 큰 데이터를 한번에 불러올 수 있음
* 여러 형태의 데이터를 하나 이상의 변수로 선언 가능
* Python에서 변수명을 한글로 선언 가능

**자료형**
* 데이터 자료형을 규명하는 것은 프로그래밍에 있어서 가장 기본적이고 중요함
* 파이썬에서는 데이터의 자료형을 변수 선언 시, 자동으로 지정
* 자료형에 따라 분석의 기법이 달라질 수 있음
* 기본적으로 3가지 자료형이 가장 많이 사용됨
  - 정수형 int: 양의 정수, 음의 정수, 0
  - 실수형 float: 정수를 포함한 실수, 0.n 형태로 출력
  - 문자형 str: 영어나 기호, 또는 숫자로 구성된 문자

In [ ]:
#파이썬에서 등호 (=) 기호는 '같다'를 의미하는 것이 아닌, '선언한다'라는 의미가 있음

a = 10
print(a)         # print(): 데이터나 변수를 출력
print(type(a))   # type(): 데이터의 타입을 확인

10
<class 'int'>


In [ ]:
b = 'B'
print(b)
print(type(b))

B
<class 'str'>


In [ ]:
num = 23.1
print(num)
print(type(num))

23.1
<class 'float'>


In [ ]:
a = 10
b = 'B'
a + b   #자료형이 일치하지 않으면 오류 발생

TypeError: ignored

In [ ]:
#Jupyter Notebook의 경우, print함수를 사용하지 않고 변수명만 입력해도 데이터 출력 가능

a = float(10)   #자료형을 임의로 바꾸려면, 데이터 앞에 타입을 입력하여 변수 선언
type(a)

float

-----

### 문자열 자료형 (String)

* 프로그래밍 뿐만 아니라, 데이터 분석에 있어서 문자를 처리하는 것이 중요
* 문자열: 문자, 단어 등으로 구성된 문자들의 집합 ex. "단어" / "A" / "123"
* 문자열에는 모두 큰따옴표(") 또는 작은따옴표(')를 이용해 선언
* 여러 줄의 문자열을 대입할 경우 큰따옴표 또는 작은 따옴표 세 개를 사용
* 문자열을 여러 형태로 연산이 가능함
* 인덱싱(indexing)과 슬라이싱(Slicing) 기능이 많이 사용됨
  - Indexing: 특정 위치의 문자를 추출
  - Slicing: 특정 위치의 문자를 잘라냄

#### String

In [ ]:
#문자를 그대로 작성하면 오류가 발생

안녕하세요

NameError: name '안녕하세요' is not defined

In [ ]:
#따옴표를 활용하여 문자형을 문자열 자료형으로 사용할 수 있음

"안녕하세요"

'안녕하세요'

In [ ]:
#여러 문장을 사용할 경우

"""
여러문장의 경우
따옴표를 세 개를 사용해 주면 됩니다.
감사합니다.
"""

'\n여러문장의 경우\n따옴표를 세 개를 사용해 주면 됩니다.\n감사합니다.\n'

In [ ]:
#문자열도 변수로 저장 가능

a = "안녕하세요"
b = """저는 문자형 입니다.
반갑습니다"""

print(a)
print(b)
type(a), type(b)

안녕하세요
저는 문자형 입니다.
반갑습니다


(str, str)

In [ ]:
#연산자를 활용해 문자열 연산 가능 (덧셈, 곱셈)

str1 = "인사이트"
str2 = "에 오신 여러분을 환영합니다."

str1 + str2

'인사이트에 오신 여러분을 환영합니다.'

In [ ]:
str3 = "감사합니다"

str3 * 3

'감사합니다감사합니다감사합니다'

In [ ]:
#len(): 해당 문자열의 길이를 구하는 함수 (데이터의 길이나 크기를 구할 떄도 사용)

str4 = "이 문자열의 길이는 len함수를 이용해 구할 수 있습니다."

len(str4)

32

#### String Indexing
* Indexing: 특정 위치의 글자 추출
* 대괄호를 이용해 추출하며, 0부터 순서가 매겨짐
* 뒷부분부터 셀 땐, 음수를 붙여 세어줄 수 있음
* 실무에서 복잡한 문자데이터를 다룰 때 (설문, 제품명, 항목명 등) 주로 사용

In [ ]:
str5 = "너의 삶은 짧지만, 계속 구하면 가치있는 것을 찾으리라"

str5[0]

'너'

In [ ]:
str5[14]

'구'

In [ ]:
str5[-2]

'리'

In [ ]:
str5[0] + str5[14] + str5[-2]

'너구리'

In [ ]:
str6 = str5[0] + str5[14] + str5[-2]
print(type(str6))
str6

<class 'str'>


'너구리'

#### String Slicing
* Slicing: 특정 글자를 잘라서 추출
* str[n:m] : str 변수의 문자열에서, n번째 부터, m번째 글자 전까지 추출
* str[:m] : 맨 처음부터 m 번째 글자 전 까지 추출
* str[n:] : n 번째 글자부터 맨 끝 글자 까지 추출
* 처음번호와 끝 번호를 생략하면 모든 문자열이 출력

In [ ]:
str5 = "발자국마다 이어진 별자리 그 서투른 걸음이 새겨놓은 밑그림"

str5[0:3]

'발자국'

In [ ]:
str5[:13]

'발자국마다 이어진 별자리'

In [ ]:
str5[16:]

'서투른 걸음이 새겨놓은 밑그림'

In [ ]:
str5[:13] + str5[16:]

'발자국마다 이어진 별자리서투른 걸음이 새겨놓은 밑그림'

In [ ]:
str7 = "2021파이썬기초"
day = str7[:4]
lesson = str7[4:]

print(day)
print(lesson)

2021
파이썬기초


#### String Function
* count() : 특정 문자의 개수를 출력
* find() / index() : 특정 문자가 어디에 위치해 있는지 출력 (index 함수의 경우, 해당 문자가 없으면 오류 발생)
* join() : 문자열에 특수기호나 특정 문자를 삽입
* upper() / lower() : 영어 소문자를 대문자로 변경 (upper) / 영어 대문자를 소문자로 변경 (lower)
* lstrip() / rstrip() / strip() : 문자열 좌,우 또는 전체 공백을 제거
* replace() : 특정 문자를 다른 문자로 변환
* split() : 문자를 공백 기준으로 리스트의 형태로 나누어 출력 (쌍반점(:) 기호 사용 시, 전체 문자열이 리스트에 하나의 객체로 출력)

In [ ]:
#count

str8 = "Insight Python Data Analyze"
str8.count('a')

3

In [ ]:
#find

str8.find("D")

15

In [ ]:
#index

str8.index("D")

15

In [ ]:
#join

",".join('가나다라마')

'가,나,다,라,마'

In [ ]:
#upper

str8.upper()

'INSIGHT PYTHON DATA ANALYZE'

In [ ]:
#lower

str8.lower()

'insight python data analyze'

In [ ]:
#lstrip

str9 = "    Python     "
str9.lstrip()

'Python     '

In [ ]:
#rstrip

str9.rstrip()

'    Python'

In [ ]:
#strip

str9.strip()

'Python'

In [ ]:
#replace

str10 = "python Big 데이터"
str10.replace('데이터', 'data')

'python Big data'

In [ ]:
#split

str10.split()

['python', 'Big', '데이터']

In [ ]:
str10.split(":")

['python Big 데이터']

#### 과제 1~2

1. 어떤 회원이 생년월일 입력란에 890724를 입력하였을 때, 해당 문자를 연/월/일로 각각 나누어 출력하기

In [ ]:
dateofbirth = "890724"

year = dateofbirth[:2]
month = dateofbirth[2:4]
day = dateofbirth[4:]

print(year)
print(month)
print(day)

89
07
24


2. 어떤 고객이 휴대전화번호를 010-1234-5678으로 입력하였을 때, 해당 문자를 01012345678으로 출력하기

In [ ]:
str1 = "010-1234-5678"

str1.replace("-", "")

'01012345678'

-----

### 리스트 (List)

* 리스트 (list) : 여러 개의 데이터 다룰 때, 하나의 변수에 많은 값을 집어 넣을 수 있음
* 대괄호를 이용하여, 데이터를 묶어 줌 ex) a = [1,2,3,4,5] #5개의 데이터가 a라는 변수에 모두 담겨있음
* C 언어의 배열(array)과 유사한 List 를 이용
* 서로 다른 데이터 타입의 값들도 하나의 List에 넣을 수 있음
* 리스트 내 데이터 간 순서가 존재
* 리스트 내 데이터를 삭제하거나 추가, 수정이 가능함
* 리스트 내 데이터를 삭제하거나 추가, 수정이 가능함
    - append() : 추가
    - insert() : 삽입
    - remove() : 삭제
* Size가 정해져 있지 않고 유동성 있음

In [ ]:
list1 = [100, 200, 300, 400, 500]
list1

[100, 200, 300, 400, 500]

In [ ]:
type(list1)

list

In [ ]:
#문자열도 리스트로 선언이 가능

list2 = ['서울', 70, 170, '강남']
list2

['서울', 70, 170, '강남']

In [ ]:
type(list2)

list

In [ ]:
#리스트에서 특정 값을 추출 (Indexing)

list1[0]

100

In [ ]:
list1[1], list1[2], list1[3]

(200, 300, 400)

In [ ]:
sub = ['국어', '영어', '수학', '과학']
sub

['국어', '영어', '수학', '과학']

In [ ]:
#append(): 리스트에 해당 값을 추가

sub.append('사회')
sub

['국어', '영어', '수학', '과학', '사회']

In [ ]:
#insert(): 리스트 특정위치에 해당 값을 추가

sub.insert(0, '한국사')
sub

['한국사', '국어', '영어', '수학', '과학', '사회']

In [ ]:
#remove(): 특정 값을 리스트에서 삭제

sub.remove('수학')
sub

['한국사', '국어', '영어', '과학', '사회']

In [ ]:
score = [10, 20, 30, 40]
score

[10, 20, 30, 40]

In [ ]:
#리스트 간 연산 가능

score * 3

[10, 20, 30, 40, 10, 20, 30, 40, 10, 20, 30, 40]

In [ ]:
score + sub

[10, 20, 30, 40, '한국사', '국어', '영어', '과학', '사회']

-----

### 튜플 (Tuple)
* 튜플 (tuple) : 리스트와 같이 여러 개의 데이터를 집어넣을 수 있는 공간
* 소괄호를 이용하여, 데이터를 묶어 줌 ex) c = (1,2,3,4,5) #5개의 데이터가 c라는 변수에 모두 담겨있음
* 튜플 내 데이터 간 순서가 존재
* 한번 선언된 튜플은 변경이 불가능 함
* Packing과 Unpacking을 활용하여, 데이터를 추출하거나 튜플을 생성할 수 있음
    - Packing : 여러 개의 데이터를 쉼표(,) 구분자를 이용해, 하나의 변수로 생성
    - Unpacking : 하나의 튜플을 여러 개의 변수로 선언하여, 변수에 각 데이터를 선언
* 함수와 반복문 같이 중요한 하이퍼파라미터(Hyper Parameter)들을 보호 할 때 사용 (하이퍼파라미터 : 수식 내 값이 변하지 않는 인자나 상수)

In [ ]:
#소괄호를 이용해 튜플 생성 가능

t1 = (1, 2, 3, 4, 5)
print(type(t1))
t1

<class 'tuple'>


(1, 2, 3, 4, 5)

In [ ]:
#튜플은 한 번 선언되면 변경이 불가능

t1.append("A")

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
t1.remove(3)

AttributeError: 'tuple' object has no attribute 'remove'

In [ ]:
#그러나 각 데이터를 하나의 튜플로부터 추출 가능

t2 = (1, 2, '삼', 4, 5)
t2[2]

'삼'

In [ ]:
#Packing: 각각의 데이터를 하나의 변수로 선언할 때, 해당 변수들을 하나의 튜플로 선언 가능

pack1 = 1,2,3,4,5,6
type(pack1)

tuple

In [ ]:
pack1

(1, 2, 3, 4, 5, 6)

In [ ]:
#Unpacking: 하나의 튜플 내 데이터를 각각의 변수로 선언 가능

a,b,c,d,e,f = pack1
type(a)

int

In [ ]:
a

1

In [ ]:
a + b + c + d + e + f

21

In [ ]:
#Indexing과 Slicing은 가능

a = (10,20,30,40,50)
a[0]

10

In [ ]:
a[-1]

50

In [ ]:
a[2:]

(30, 40, 50)

In [ ]:
#기본 연산자를 이용한 연산 가능

b = (1, 2, 3, 4)
c = (5, 6, 7, 8)
c + b

(5, 6, 7, 8, 1, 2, 3, 4)

In [ ]:
c * 2

(5, 6, 7, 8, 5, 6, 7, 8)

-----

### 세트 (Set)

* 세트 (Set) : 리스트와 같이 여러 개의 데이터를 집합의 형태로 집어넣을 수 있는 공간
* 중괄호를 이용하여, 데이터를 묶어 줌  ex) c = {1,2,3,4,5} #5개의 데이터가 c라는 변수에 모두 담겨있음
* 집합 내 데이터 간 순서 없음, 중복을 허용하지 않음
* 집합 내 데이터 변경이 가능
* 집합연산이 가능 (Van Diagram의 개념)

In [ ]:
#중복된 값은 스스로 제외하고 출력

A = {10,20,30,40,10}
print(A)
print(type(A))

{40, 10, 20, 30}
<class 'set'>


In [ ]:
B = {10,10,10,10,10,10}
print(B)

{10}


In [ ]:
#괄호 내부에 있는 list를 set 형태로 선언

S = set([1,2,3,4,5,6])
print(S)
print(type(S))

{1, 2, 3, 4, 5, 6}
<class 'set'>


In [ ]:
C = {10,20,30,40,50}
D = {40,50,60,70}

#교집합 연산
print(C&D)

#합집합 연산
print(C|D)

#차집합 연산: C 집합에서 D 집합의 원소를 뺸 나머지
print(C-D)

#대상 차집합 연산: 교집합을 제외한 나머지 원소 출력
print(C^D)

{40, 50}
{70, 40, 10, 50, 20, 60, 30}
{10, 20, 30}
{70, 10, 20, 60, 30}


* A.intersection(B) : A와 B의 교집합을 연산 (A&B와 같은 결과)
* A.union(B) : A와 B의 합집합을 연산 (A|B와 같은 결과)
* A.difference(B) : A와 B의 차집합을 연산 (A-B와 같은 결과)
* A.add(n) : A의 Set에 n이라는 값을 추가
* A.update([n1,n2,n3]) : A의 Set에 [n1,n2,n3]의 여러 값을 추가

In [ ]:
print(C.intersection(D))
print(C.union(D))
print(C.difference(D))

{40, 50}
{70, 40, 10, 50, 20, 60, 30}
{10, 20, 30}


In [ ]:
C.add(100)
C

{10, 20, 30, 40, 50, 100}

In [ ]:
C.update([1,2,3,4,5])
C

{1, 2, 3, 4, 5, 10, 20, 30, 40, 50, 100}

-----

### 딕셔너리 (Dictionary)

* 딕셔너리 (Dictionary) : 데이터를 Key와 Value의 Pair 형태로 하나의 변수에 선언
* 중괄호를 이용하여, key-value Pair 형태로 묶어줌  
    ex) d = {“name” : “Kim”, “value” : 100 } -> Kim이라는 데이터가 name이라는 키값과 쌍을 이룸. 100이라는 데이터가 value라는 키값과 쌍을 이룸.
* 매우 많이 사용되는 데이터 자료형 중 하나
* 데이터를 구조적으로 다룰 수 있음
* Key 값은 중복 되지 않음
* 이후, Pandas 라이브러리의 Series 와 비슷한 개념

In [ ]:
D = {'A':100, 'B':200, 'C':300}
print(D)
print(type(D))

{'A': 100, 'B': 200, 'C': 300}
<class 'dict'>


In [ ]:
dict1 = {"이름":"제니", "전공":"경영", "학번":17}
dict1

{'이름': '제니', '전공': '경영', '학번': 17}

In [ ]:
#D['Key']: D라는 딕셔너리의 Key값에 해당하는 Value값을 출력

dict1['이름']

'제니'

In [ ]:
#D.get('Key'): D라는 딕셔너리의 Key값에 해당하는 Value값을 출력

dict1.get('전공')

'경영'

In [ ]:
#D.keys() : D라는 딕셔너리의 Key값을 모두 가져옴

dict1.keys()

dict_keys(['이름', '전공', '학번'])

In [ ]:
#D.value() : D라는 딕셔너리의 Value 값을 모두 가져옴

dict1.values()

dict_values(['제니', '경영', 17])

In [ ]:
#딕셔너리의 Value값도 List 형태로 넣을 수 있음

dict1['이름'] = ['로제', '리사']
dict1['전공'] = ['경영학', '수학']
dict1['학번'] = [16, 19]
dict1

{'이름': ['로제', '리사'], '전공': ['경영학', '수학'], '학번': [16, 19]}

In [ ]:
#딕셔너리와 리스트를 이용하여, 해당 Key 값에 Value를 계속 추가해 줄 수 있음

names = ["제니"]
majors = ['경영']
classes = [17]

dict3 = {"이름": names, '전공':majors, "학번": classes}
dict3

{'이름': ['제니'], '전공': ['경영'], '학번': [17]}

In [ ]:
names.append('지수')
majors.append('경영학')
classes.append(19)

In [ ]:
dict3 = {"이름": names, '전공':majors, "학번": classes}
dict3

{'이름': ['제니', '지수'], '전공': ['경영', '경영학'], '학번': [17, 19]}

#### 과제 3

3. 간단한 영한 사전 만들기 -> 1부터 10까지 영어를 입력하면 한글로 출력되는 프로그램
  
  (input 함수를 이용해서 값을 입력 받을 수 있음, Key-Value Pair를 이용해 프로그램 제작)

In [ ]:
num_dict = {"one":"일",
            "two":"이",
            "three":"삼",
            "four":"사",
            "five":"오",
            "six":"육",
            "seven":"칠",
            "eight":"팔",
            "nine":"구",
            "ten":"십"}

eng_num = input("Enter number : ")
kor_num = num_dict.get(eng_num)

print(kor_num)

Enter number : one
일


-----

### 기본 연산자

* 산술 연산자
  - 연산의 우선순위 존재 : 거듭제곱 -> 곱셈 및 나눗셈 -> 나머지 및 몫 -> 덧셈 뺄셈 연산 (연산의 순위가 같을 경우, 왼쪽에서 오른쪽으로 연산 진행)

* 비교 연산자
  - 두 개의 연속형 데이터를 비교
  - 명제가 맞는 경우 True, 틀린 경우 False의 Bool 형태 결과를 출력 (Boolean : 참 또는 거짓을 나타내는 자료형)
  - Boolean의 경우 조건문에서 많이 사용

* 논리 연산자
  - And / Or / Not : ~이고, 그리고 / ~이거나, 또는 / ~이 아니다

In [ ]:
a = 100
b = 35

In [ ]:
#쉼표를 이용해, 여러 개의 결과를 동시에 출력 가능

a+b, a-b

(135, 65)

In [ ]:
a*b, a/b

(3500, 2.857142857142857)

In [ ]:
a//b, a%b

(2, 30)

In [ ]:
a = 50
b = 67

a>b, a<b

(False, True)

In [ ]:
a>=b, a<=b

(False, True)

In [ ]:
a==b

False

In [ ]:
a!=b

True

In [ ]:
#결과에 대한 자료형을 type() 기능을 이용해 파악 가능

type(a!=b)

bool

#### 과제 4~5

4. 값을 입력 받아 원의 넓이를 구하는 프로그램 만들기

 * input 함수를 이용해서 값을 입력 받을 수 있음, 입력 받은 변수를 활용해 계산식 세우기
 * 원 넓이 구하는 공식 : y = π x r² (π= 3.14 로 계산))

In [ ]:
radius = input("반지름의 값을 입력하시오 : ")

area = 3.14 * int(radius) ** 2

print(area)

반지름의 값을 입력하시오 : 3
28.26


5. 금액을 입력했을 때, 상품 가격에 따른 잔돈을 반환하는 자판기 프로그램 만들기
    - 금액과 상품가격은 input함수로 선언
    - 잔돈은 500,100,50,10원 단위로 반환
    - 잔돈은 가장 큰 금액부터 반환 예) 잔돈 760원 : 500원1개, 100원2개, 50원 1개, 10원 1개

In [ ]:
payment = int(input("금액을 입력하시오 : "))
price = int(input("가격을 입력하시오 : "))
change = payment - price
full_change = change

coin_500 = change // 500
change %= 500

coin_100 = change // 100
change %= 100

coin_50 = change // 50
change %= 50

coin_10 = change // 10
change %= 10

print(f"잔돈 {full_change}원 : 500원{coin_500}개, 100원{coin_100}개, 50원{coin_50}개, 10원{coin_10}개")

금액을 입력하시오 : 1140
가격을 입력하시오 : 550
잔돈 590원 : 500원1개, 100원0개, 50원1개, 10원4개


-----

##  Statement & Function

### 조건문 (if)

* 조건문 : 특정 상황에 대한 판단 또는 해당 조건에 대한 실행여부 결정
* If문을 사용하여 구현함
* 들여쓰기를 이용해, 해당 조건에 대한 수행문의 종속을 표현
* 주로 비교 연산자와 함께 사용됨
* 특히 데이터 전처리를 할 때, apply 함수와 함께 매우 많이 사용됨

In [ ]:
#if 조건문을 이용한 연속형 변수 비교

A = 100
B = 200

if A>B:
    print("Hi")
else:
    print("안녕하세요")

안녕하세요


In [ ]:
#입력 함수를 이용하여 숫자를 비교하는 프로그램

C = int(input("첫번째 정수를 입력하세요 : "))
D = int(input("두번째 정수를 입력하세요 : "))

if C>D:
    print("첫번째 정수 ",C,"가 더 큽니다.")
else :
    print("두번째 정수 ",D,"가 더 큽니다.")

if C==D:
    print("첫번째 정수와 두번째 정수가 같습니다.")
else:
    print("첫번째 정수와 두번째 정수가 다릅니다.")

첫번째 정수를 입력하세요 : 10
두번째 정수를 입력하세요 : 55
두번째 정수  55 가 더 큽니다.
첫번째 정수와 두번째 정수가 다릅니다.


- 여러 가지 조건을 동시에 판별할 땐, elif 구문을 이용
- elif문은 개수의 제한 없이 사용 가능
- 특정 조건에 수행할 문장을 사용하지 않을 땐, Pass 구문을 이용

In [ ]:
#if문을 이용한 성적처리 프로그램

score = int(input("성적을 입력하세요! : "))

if score >= 95:
    print("학생의 성적은 A+입니다.")
elif score >= 90:
    print("학생의 성적은 A입니다.")
elif score >=80 :
    print("학생의 성적은 B입니다.")
elif score >=70 :
    print("학생의 성적은 C입니다.")
else:
    print("학생의 성적은 F입니다.")

성적을 입력하세요! : 98
학생의 성적은 A+입니다.


In [ ]:
#Pass 구문의 사용

A,B = 100, 20

if A>B:
    pass
else:
    print("Error")

#### 과제 6

6. 값을 입력 받아 홀수인지 짝수인지 판별하는 프로그램 만들기

In [ ]:
num = int(input("값을 입력하시오 : "))

if num % 2 == 0:
  print("짝수")
else:
  print("홀수")

값을 입력하시오 : 7
홀수


-----

### 반복문 (While, For)

* 반복문 : 특정 수식이나 기능을 반복 수행할 때 사용
* 특정 조건이 맞을 때, 계속 반복되는 구조
* 들여쓰기를 이용해, 반복 조건에 대한 수행문의 종속을 표현
* 주로 수학연산에서 사용
* 데이터 전처리를 할 때, 문자열 처리에서 많이 사용됨



#### While문

In [ ]:
i = 0

while i <5:
    print("Hi Python~!")
    i = i+1

print("반복종료")

Hi Python~!
Hi Python~!
Hi Python~!
Hi Python~!
Hi Python~!
반복종료


In [ ]:
#While문은 일반적으로 특정 조건만 만족되면 수행문이 반복되기 때문에
#중간에 수행문을 멈출 조건을 걸어줘야 함

i=1
while i>0:
    print("Hello")
    i = i+1

    if i>3 :
        print("강제 탈출")
        break             #break문을 이용하면, 바로 While문을 나올 수 있음.

print("반복종료")

Hello
Hello
Hello
강제 탈출
반복종료


#### for문

In [ ]:
#For문은 기본적으로 range( ) 함수와 같이 사용이 됨

for i in range(1,10):  # range(0,n+1) : 0부터 n까지의 범위를 부여한다.
    print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
#여러 가지 자료형을 이용한 For 문

list1 = ['a','b','c','d']
for i in list1:
    print(i)

a
b
c
d


In [ ]:
a = [(1,2),(3,4),(5,6)]
for (n1,n2) in a:
    print(n1+n2)

3
7
11


In [ ]:
# for문과 if문을 같이 사용한 경우 (자동업무 구현에 많이 사용)

score = [100,23,30,76,34,50]
num=0

for i in score:
    num = num+1
    if i>60:
        print("합격입니다.")
    else:
        print("불합격입니다.")

합격입니다.
불합격입니다.
불합격입니다.
합격입니다.
불합격입니다.
불합격입니다.


In [ ]:
# 1부터 n까지 더하는 프로그램

sum = 0

for i in range(1,101):
    sum=sum+i

print(sum)

5050


#### 과제 7~8

7. For 반복문을 중첩하여, 아래와 같이 * 기호를 피라미드로 출력하는 프로그램 제작

In [ ]:
i = 1

for i in range(1, 6):
  for j in range(1, i+1):
    print("*", end = "")
  print()

*
**
***
****
*****


8. For문과 If문을 이용하여, 아래의 리스트의 최댓값을 구하는 프로그램 제작

    list = [1,24,3,44,1000,2,0,74] / 결과 : 1000

In [ ]:
list = [1, 24, 3, 44, 1000, 2, 0, 74]
max = 0

for i in list:
  if i > max:
    max = i

print(max)

1000


-----

### 함수
* 함수 : 입력 X 값에 대한 결과 Y값을 반환(Return)하는 기능을 하나의 묶음으로 선언
* Input X 와 Output Y
* 반복적으로 사용되는 특별한 기능을 함수로 선언
* 여러 함수들의 집합을 ‘모듈(module)’이라고 부름
* 복잡한 데이터를 전처리할 때, 특정 기능을 반복적으로 구현하고 싶을 때 사용



In [ ]:
#함수는 코드가 진행될 때, 함수 이름이 언급되지 않으면 실행 되지 않음
#입력 받은 수의 합을 구하는 함수

def sum(num):
    for i in range(1,num+1):
        sum = num*(num+1)/2
    return sum

num = int(input('정수를 입력하시오 : '))
sum(num)

정수를 입력하시오 : 12


78.0

In [ ]:
#한번 선언된 함수는 다른 코드 입력 창에서 입력을 해도 사용 가능

def circle_area(r):
    return (r**2)*(3.14)

In [ ]:
data = 1000
circle_area(data)

3140000.0

In [ ]:
# 두 개의 입력 값을 받아 하나의 결과 값을 출력

def cylinder_volume(r,h):
    return (r**2)*(3.14)*h

num1 = 1000
num2 = 2000

cylinder_volume(num1,num2)

6280000000.0

In [ ]:
#하나의 값을 입력해 여러 개의 결과 값을 출력

def timetable(data):
    list1 = [data * 1, data * 2, data * 3]
    return list1[0], list1[1], list1[2]

timetable(5)

(5, 10, 15)

In [ ]:
# 날짜 데이터를 함수를 이용해 처리

def datetime(date):
    date = str(date)
    result1 = date[0:4]+"-"+date[4:6]+"-"+date[6:]
    return result1

datetime(20210301)

'2021-03-01'

#### 과제 9

9. 입력하는 모든 수의 평균을 계산하는 함수 만들기

In [ ]:
def means(*args):    #입력 개수에 상관없이 사용하기 위해, 함수 입력 값 자리에 *args를 사용
  total = 0
  for num in args:
    total += num
  avg = total / len(args)
  return avg

print(means(1, 5, 6, 7, 222))

48.2


-----

### 라이브러리 (Numpy & Pandas)

* 모듈 : 여러 함수들을 모아놓은 집합
* 라이브러리 : 특정 기능을 지원하는 모듈 및 함수를 모아놓은 집합
* 기능에 따라 여러 가지 라이브러리가 존재 (시각화, 웹 서비스, 데이터 분석, 머신러닝, 등…)
* 필요에 따라 라이브러리를 직접 만들기도 함
* Anaconda를 설치하면, 데이터 분석에 필요한 기본 라이브러리들이 포함되어 설치됨
* 데이터 분석에서 기초적으로 Numpy 와 Pandas 를 많이 사용

#### Numpy

- Numpy : Numeric + Python의 약자 , 수학 및 과학 연산 라이브러리
- 배열이나 행렬계산에 필요한 함수 제공
- 수열 데이터를 다룰 때 용이, 이후에 Pandas에서 DataFrame 형태로 사용
- 다차원 배열(Array)를 다룰 때 주로 사용 (인공신경망, 비정형 데이터 처리, 자연어 처리 등)

In [ ]:
#Numpy 라이브러리 호출하여, np라는 약자로 사용
#Numpy 내에 함수를 사용할 때, 반드시 np라는 문자를 붙임

import numpy as np

In [ ]:
#에러 발생 - 리스트의 경우 통계연산이 불가능

data = [6,5,7,3,4,2]
data.mean()

AttributeError: 'list' object has no attribute 'mean'

In [ ]:
#다차원 배열(ndarray)의 경우 통계를 포함한 모든 수학적 연산 지원

arr = np.array(data)
arr.mean()

4.5

In [ ]:
#리스트와 배열의 데이터 타입

print(type(data))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#배열 내부에는 여러 형태의 데이터 타입이 올 수 있음
#변수 선언 시 자동으로 데이터 타입 결정

arr1 = np.array([1,2,3,4,5])
arr1.dtype

dtype('int32')

In [ ]:
arr2 = np.array([1.1, 2.3, 3.4, 4.5, 5.3])
arr2.dtype

dtype('float64')

In [ ]:
arr3 = np.array(['A', 'B', 'C', 'D', 'E'])
arr4 = np.array(['제니', '로제', '지수', '리사'])
print(arr3)
print(arr4)
print(arr3.dtype)
print(arr4.dtype)

['A' 'B' 'C' 'D' 'E']
['제니' '로제' '지수' '리사']
<U1
<U2


In [ ]:
#이중 리스트를 이용해 행렬(Matrix)을 구현 가능
# 3X3 행렬의 구현

data = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
matrix = np.array(data)
print(type(matrix))
matrix

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 행렬간 사칙연산

matrix = np.array([[1,2],[2,3],[19,30]])
matrix

array([[ 1,  2],
       [ 2,  3],
       [19, 30]])

In [ ]:
matrix_2 = np.array([[3,4],[5,6],[3,5]])
matrix_2

array([[3, 4],
       [5, 6],
       [3, 5]])

In [ ]:
print(matrix * matrix_2)
print("---------------")
print(matrix - matrix_2)

[[  3   8]
 [ 10  18]
 [ 57 150]]
---------------
[[-2 -2]
 [-3 -3]
 [16 25]]


In [ ]:
#행렬의 제곱연산

matrix **2

array([[  1,   4],
       [  4,   9],
       [361, 900]], dtype=int32)

In [ ]:
#shape: 행렬의 구조 출력, n개의 행의 m개의 열로 구성된 행렬은 (n,m)으로 출력

arr_b = np.array([[1,2,],[2,3]])
arr_b.shape

(2, 2)

* np.arange(n) : 0부터 n까지의 값을 가지는 배열 생성
* np.arange(n,m) : n부터 m-1 까지 값을 갖는 배열 생성
* np.arrange(n,m,k) : n부터 m-1 까지 k씩 증가시켜 배열 생성
* np.random.randn(n) : 평균이 0이고 표준편차가 1인 n개의 데이터를 무작위로 생성
* np.random.randn(n,m) : 평균이 0이고 표준편차가 1인 n개의 데이터를 nxm 행렬의 형태로 생성

In [ ]:
# arange함수를 이용한 데이터 자동 생성

arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr6 = np.arange(1,10,2)
arr6

array([1, 3, 5, 7, 9])

In [ ]:
#Random data 생성

arr7 = np.random.randn(10)
arr7

array([ 1.23889136, -1.47211317,  0.38685757, -0.10427473, -1.42803008,
        1.2263063 , -0.16590523, -0.56937511, -1.58243235, -0.75226956])

In [ ]:
arr8 = np.random.randn(10,5)
arr8

array([[-0.46042006,  1.72785639, -0.51891677, -0.05051558,  0.0881807 ],
       [ 0.35765097,  1.49757302, -0.18460514,  1.45659398, -1.39350092],
       [-1.1722245 ,  0.5144245 ,  2.2163723 , -0.172401  ,  0.76720529],
       [ 0.34934313,  0.65725699,  0.44549073,  0.02687649, -0.15210592],
       [-1.41082442, -1.59686641,  1.86054399,  0.91840974, -0.5341845 ],
       [ 0.46894111, -0.02401727,  1.82520891,  0.11814694,  0.12028387],
       [ 0.27845926, -1.639913  ,  1.88758496, -0.80645272,  1.07416346],
       [-0.35472506,  0.14615081,  0.58465831, -0.98401746,  0.4404132 ],
       [-0.43130607, -0.75616671,  1.61849884, -0.23425771,  0.83413873],
       [-0.29737723,  0.18904842,  0.69177539, -0.08812423,  0.61166829]])

In [ ]:
#np.astype( ) : 현재 array내 데이터를 원하는 형태의 데이터 타입으로 변경

arr = np.array([1,2,3,4,5])
print("before ",arr.dtype)

arr = arr.astype(np.float)
print("After ",arr.dtype)
arr

before  int32
After  float64


array([1., 2., 3., 4., 5.])

In [ ]:
# 2차원 array에서 Indexing

arr_1 = np. array([[1,2,5],[4,5,9],[6,7,34]])
arr_1

array([[ 1,  2,  5],
       [ 4,  5,  9],
       [ 6,  7, 34]])

In [ ]:
arr_1[0,0]

1

In [ ]:
arr_1[2,1]

7

In [ ]:
arr_1[:,0]

array([1, 4, 6])

In [ ]:
arr_1[0,:]

array([1, 2, 5])

In [ ]:
#행 또는 열 형태로 출력

arr_1[0:2, :]

array([[1, 2, 5],
       [4, 5, 9]])

In [ ]:
arr_1[:, 0:2]

array([[1, 2],
       [4, 5],
       [6, 7]])

In [ ]:
arr_1[:,:]

array([[ 1,  2,  5],
       [ 4,  5,  9],
       [ 6,  7, 34]])

In [ ]:
# 전체 데이터 shape 변환하기

print(arr_1)
print("------------")
print(arr_1.reshape(1,9))

[[ 1  2  5]
 [ 4  5  9]
 [ 6  7 34]]
------------
[[ 1  2  5  4  5  9  6  7 34]]


In [ ]:
#값 초기화하기

arr_z = np.zeros((2,2))
arr_z

array([[0., 0.],
       [0., 0.]])

In [ ]:
arr_x = np.zeros(10)
arr_x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_c = np.ones(10)
arr_c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#배열 합 구하기 (전체합, 행 방향 합, 열 방향 합)

arr1 = np.arange(1,11).reshape(5,2)
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
arr1.sum()  #전체합

55

In [ ]:
arr1.sum(axis=1) #행 방향합

array([ 3,  7, 11, 15, 19])

In [ ]:
arr1.sum(axis=0)

array([25, 30])

#### Pandas

* Pandas : 데이터 과학에 사용되는 라이브러리로 데이터 불러오기, 전처리, 통계 분석에 사용
* Numpy 기반으로 작성된 라이브러리
* Series 형태와 DataFrame 형태 존재
* 실무에서 접하는 엑셀 파일이 DataFrame 형태
* 데이터 분석에 있어서 필수적인 라이브러리
* 데이터 전처리에 대부분은 Pandas로 이루어 짐

⇒ 교육세션 시간에 더 자세히 살펴볼 예정

In [ ]:
#Pandas 라이브러리를 호출하여, pd라는 약자로 사용

import pandas as pd

In [ ]:
#Series의 기본적인 구조: 값(Value)과 순서(Index)로 구성

s1 = pd.Series([1,2,56,77,93])
s1

0     1
1     2
2    56
3    77
4    93
dtype: int64

In [ ]:
s1.values

array([ 1,  2, 56, 77, 93], dtype=int64)

In [ ]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#Series는 통계적 연산 가능

s1.mean()

45.8

In [ ]:
#여러 가지 Python 데이터 타입으로 Series 생성 가능

s2 = pd.Series(['제니','로제','지수','리사'], name ='출석부',
               index=['일','이','삼','사'])
s2

일    제니
이    로제
삼    지수
사    리사
Name: 출석부, dtype: object

In [ ]:
myDict = {'name':"Jenny","age":27,"gender":"female","job":"singer"}
person = pd.Series(myDict, name="Person")
person

name       Jenny
age           27
gender    female
job       singer
Name: Person, dtype: object

In [ ]:
#Series도 [ ] 기호를 이용해 Indexing 가능

person[0]

'Jenny'

In [ ]:
person['job']

'singer'

In [ ]:
person[:]

name       Jenny
age           27
gender    female
job       singer
Name: Person, dtype: object

In [ ]:
#비교 연산자를 이용해, 특정 데이터의 존재 여부를 알 수 있음

person == 'female'

name      False
age       False
gender     True
job       False
Name: Person, dtype: bool

In [ ]:
person[person == 'female']

gender    female
Name: Person, dtype: object

In [ ]:
#describe(): 다양한 통계량 요약, 데이터 파악 시 굉장히 많이 사용

obj = pd.Series([2,3,7,8], index=['d','a','b','c'])
obj.describe()

count    4.00000
mean     5.00000
std      2.94392
min      2.00000
25%      2.75000
50%      5.00000
75%      7.25000
max      8.00000
dtype: float64

In [ ]:
#sort_values로 series의 값 정렬 가능

obj.sort_values()   #내림차순 정렬 시 ascending=False 설정

d    2
a    3
b    7
c    8
dtype: int64

In [ ]:
#sort_index로 series의 순서(인덱스) 정렬 가능

obj.sort_index()

a    3
b    7
c    8
d    2
dtype: int64

In [ ]:
#value_counts로 series의 unique한 값의 수 집계

obj.value_counts()

2    1
3    1
7    1
8    1
dtype: int64

#### 과제 10~11

10. (5,2)의 random한 Matrix를 생성하고,
Matrix의 전체합, 전체 평균, 각 열의 합, 각행의 합, 각 열의 평균, 각 행의 평균을 계산하기

In [ ]:
import numpy as np

num_matrix = np.random.randn(5, 2)
print(num_matrix)
print(f"전체 합 : {num_matrix.sum()}")
print(f"전체 평균 : {(num_matrix.sum()) / (5 * 2)}")
print(f"각 열의 합 : {num_matrix.sum(axis = 0)}")
print(f"각 행의 합 : {num_matrix.sum(axis = 1)}")
print(f"각 열의 평균 : {num_matrix.sum(axis = 0) / 5}")
print(f"각 행의 평균 : {num_matrix.sum(axis = 1) / 2}")

[[ 2.07842173 -0.55448579]
 [-2.14790882  0.03623932]
 [ 1.34647103  1.13335082]
 [ 0.80114895  0.63222252]
 [-1.15860757  0.65097907]]
전체 합 : 2.8178312663793967
전체 평균 : 0.2817831266379397
각 열의 합 : [0.91952532 1.89830594]
각 행의 합 : [ 1.52393594 -2.1116695   2.47982185  1.43337146 -0.50762849]
각 열의 평균 : [0.18390506 0.37966119]
각 행의 평균 : [ 0.76196797 -1.05583475  1.23991093  0.71668573 -0.25381425]


11. Series를 이용하여, 아래와 같은 성적표를 만들기
 - 1) 각 과목의 합격/불합격 여부 출력하기 (50점 이상 , 합격)
 - 2) 과목의 전체평균을 계산하여, 70점 기준으로 합격 불합격 여부 판별하기



In [ ]:
import pandas as pd

#1
grade = {'국어':70,"영어":30,"수학":80,"과학":90}
final = pd.Series(grade, name = "성적표")

list1 = []
list2 = []

for subject, score in grade.items():
    if score >= 50:
        list1.append(f'{subject}    {score}')
    else:
        list2.append(f'{subject}    {score}')

print("합격")
for i in list1:
    print(i)

print("불합격")
for i in list2:
    print(i)

합격
국어    70
수학    80
과학    90
불합격
영어    30


In [ ]:
#2
grade = {'국어':70,"영어":30,"수학":80,"과학":90}
final = pd.Series(grade, name = "성적표")

total = 0
for subject, score in grade.items():
  total += score

avg = total / len(grade)

if avg < 70:
  print("전체불합격")
else:
  print("전체합격")

전체불합격
